services:
  myvideos-sync:
    image: yin2hao/myvideos-sync:0.1.6
    container_name: "${CONTAINER_NAME}"
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    environment:
      MYVIDEOS_SYNC_LISTEN_ADDR: "${MYVIDEOS_SYNC_LISTEN_ADDR}"
      MYVIDEOS_SYNC_API_TOKEN: "${MYVIDEOS_SYNC_API_TOKEN}"
      MYVIDEOS_SYNC_ROOT_PATH: "${MYVIDEOS_SYNC_ROOT_PATH}"
      MYVIDEOS_SYNC_PARALLEL_SCANS: "${MYVIDEOS_SYNC_PARALLEL_SCANS}"
      MYVIDEOS_SYNC_PARALLEL_COPIES: "${MYVIDEOS_SYNC_PARALLEL_COPIES}"
      MYVIDEOS_SYNC_REQUEST_TIMEOUT: "${MYVIDEOS_SYNC_REQUEST_TIMEOUT}"
      MYVIDEOS_SYNC_TRANSFER_TIMEOUT: "${MYVIDEOS_SYNC_TRANSFER_TIMEOUT}"
      PRIMARY_WEBDAV_URL: "${PRIMARY_WEBDAV_URL}"
      PRIMARY_WEBDAV_USERNAME: "${PRIMARY_WEBDAV_USERNAME}"
      PRIMARY_WEBDAV_PASSWORD: "${PRIMARY_WEBDAV_PASSWORD}"
      DISASTER_WEBDAV_URL: "${DISASTER_WEBDAV_URL}"
      DISASTER_WEBDAV_USERNAME: "${DISASTER_WEBDAV_USERNAME}"
      DISASTER_WEBDAV_PASSWORD: "${DISASTER_WEBDAV_PASSWORD}"
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
